### ISSUE TITLE
Tips on how to get UTI for apps?

### ISSUE THREAD

**Issue by gandalfsaxe** [jwkicklighter/dotfiles#2]
What are some good ways of obtaining the identifying UTI for an app, e.g. `com.microsoft.VSCodeInsiders` for VSCode? Is there both a way using Terminal and Finder?

I'd ask in the [reddit thread](https://www.reddit.com/r/mac/comments/8u9wne/wrote_a_simple_script_that_uses_duti_to_change/), but it's archived now :)

**Comment by gandalfsaxe** [comment]
Found some good references here:

https://stackoverflow.com/questions/39464668/how-to-get-bundle-id-of-mac-application

https://www.chainsawonatireswing.com/2012/09/19/changing-default-applications-on-a-mac-using-the-command-line-then-a-shell-script/

In a nutshell: I use `osascript -e 'id of app "SomeApp"'`, in a slightly longer version to also to into /Applications and back + copy to clipboard: `cd /Applications && osascript -e 'id of app "Visual Studio Code"' | pbcopy && pbpaste && cd - >/dev/null && printf '\n(copied to clipbord)\n\n'`

**Comment by jwkicklighter** [comment]
Hey, thanks for this tip! I'll try to get around to modifying the script to do that
